:iabbrev em me
:iabbrev waht what
:iabbrev tihs this
:iabbrev wehn when
:iabbrev si is
:iabbrev thn than
:iabbrev worte wrote
:iabbrev teh the
:iabbrev ot to
:iabbrev bild build
:iabbrev buld build
:iabbrev adn and
:iabbrev logn long
:iabbrev tiem time
:iabbrev typign typing
